### ISSUE TITLE
Task for generating migration that fixes columns

### ISSUE THREAD

**Issue by pdabrowski6** [tcopeland/nullalign#2]
How about creating something like `bundle exec nullalign:fix` that will create a migration file which will update columns?

**Comment by tcopeland** [comment]
Interesting, good idea, @pawel-dabrowski6 , I'll look at that.

**Comment by bobwhitelock** [comment]
For what it's worth, in case this is useful to anyone until/unless this feature becomes part of this Gem, I wrote a quick script to generate the lines to put in a migration to fix the missing constraints flagged up (since my project was missing quite a few constraints and I also wanted to be able to re-run the script later).

The initial version is [here](https://github.com/alces-software/alces-flight-center/blob/a1108014ebc0580f8f07df8880649fbf895079db/bin/generate-needed-null-constraint-migrations), which doesn't contain anything specific to my app and you should be able to just run it and copy across the output to a migration.

A slightly improved version, which allows skipping certain unneeded columns is [here](https://github.com/alces-software/alces-flight-center/blob/ce6dad680b7a368d968d1bcf2b75bb0216bc65a1/bin/generate-needed-null-constraint-migrations); in this case you will of course need to alter `TABLE_AND_COLUMNS_TO_SKIP` to contain columns specific to your own app.

**Comment by tcopeland** [comment]
Thanks for the suggestion @pdabrowski6 and thanks for the comment @bobwhitelock - I've released v0.0.3 of nullalign and it includes a `nullalign:fix` Rake task.
